version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  node_app:
    build: .
    ports:
      - 8080:8080
    environment:
      APP_NAME: food_delivery
      PORT: 8080
      MONGO_URL: mongodb://mongo_db:27017/foods
    depends_on:
      - mongo_db
  
  front_end:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:5173"
    depends_on:
      - node_app
      
volumes:
  mongo_db: {}
